In [11]:
# imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
header = [
    "Tweet Id", 
    "Username", 
    "Timestamp", 
    "#Followers",
    "#Friends",
    "#Retweets",
    "#Favorites",
    "Entities",
    "Sentiment",
    "Mentions",
    "Hashtags",
    "URLs"]

data = pd.read_csv("/Users/amarjyotkaur/Downloads/TweetsCOV19.tsv.gz", compression='gzip', names=header, sep='\t', quotechar='"')

In [13]:
data[200:220]

,Tweet Id,Username,Timestamp,#Followers,#Friends,#Retweets,#Favorites,Entities,Sentiment,Mentions,Hashtags,URLs
200,1179008230267244544,554dbe766d7fc8efe5bc063f7983aec6,Tue Oct 01 12:20:41 +0000 2019,124,1143,0,0,null;,1 -1,ColtsCheer,null;,null;
201,1179008238639038467,62d93c85438ee901b3c3eda493af6b16,Tue Oct 01 12:20:43 +0000 2019,1573,730,0,0,don t get me wrong:Don%27t_Get_Me_Wrong:-1.626...,2 -3,Studdyboy3,null;,null;
202,1179008390879678464,b2f85ea0790902a937a1fbda82ef2ab7,Tue Oct 01 12:21:19 +0000 2019,1057,4324,3,3,directed energy weapons:Directed-energy_weapon...,3 -5,null;,null;,null;
203,1179009206759747584,e14c2631b27966dd2b81810e1b27219d,Tue Oct 01 12:24:34 +0000 2019,14989,345,37,37,great lakes:Great_Lakes:-1.8485635302128964;pr...,3 -1,null;,null;,https://www.cpc.ncep.noaa.gov/products/predict...
204,1179011598259613702,22066342c15dbd31943d79997b07240b,Tue Oct 01 12:34:04 +0000 2019,843,596,0,0,null;,1 -1,DerHerzeleid,null;,null;
205,1179012680960610307,b05bd92b083d78aadb7a4ca6aac46802,Tue Oct 01 12:38:22 +0000 2019,231,200,14,8,parole:Parole:-2.4663899589063116;cfrp:Carbon_...,2 -1,hernan032929 SpoxUSCIS marcorubio MarioDB Sena...,"CFRP, continueCubanCFRP",https://www.washingtonpost.com/national/would-...
206,1179013007550111744,906bc6d8667d144fd46f429fa8c0e54f,Tue Oct 01 12:39:40 +0000 2019,79,69,0,0,country:List_of_sovereign_states:-1.8064544397...,3 -2,GOPChairwoman realDonaldTrump,null;,null;
207,1179014041865461760,a525bb9c1642aa9d18f3eb82cf005e05,Tue Oct 01 12:43:47 +0000 2019,2578,2287,2,1,bon scott:Bon_Scott:-0.8640044248832468;pop cu...,1 -1,null;,ACDC music movies,http://www.whenitwascool.com/1980-guide-to-whe...
208,1179014890817761285,8c161a1390770ee2af3b9a77bfa7a56f,Tue Oct 01 12:47:09 +0000 2019,1117,244,0,0,yorkshire terrier:Yorkshire_Terrier:-0.8849325...,1 -1,null;,null;,https://lostdogsminnesota.tumblr.com/post/1880...
209,1179015138285887490,777415a09173520b920897615ecf7214,Tue Oct 01 12:48:08 +0000 2019,280,524,0,0,confucius:Confucius:-1.5642191899923834;a dang...,1 -2,null;,art Rebelion Xianjiang Confucius Mindfulness c...,null;
210,1179015296016945153,ae53ebe9dfa03645f2385ab3725e3f2d,Tue Oct 01 12:48:46 +0000 2019,1249,415,1,0,ecmo:Extracorporeal_membrane_oxygenation:-2.24...,1 -1,null;,FOAMed FOAMems,https://edecmo.org/58-first-american-pre-hospi...
211,1179016010667569152,0e3815c542df551febe680b5da558107,Tue Oct 01 12:51:36 +0000 2019,847,864,0,0,null;,1 -1,iamcee_j,null;,null;
212,1179017394812899334,d4d1ed438ffd068b6a0d1ca94b94c025,Tue Oct 01 12:57:06 +0000 2019,307,360,0,0,null;,2 -1,null;,null;,null;
213,1179018288187281409,0974e2dc580142cbca10909d20d5bad8,Tue Oct 01 13:00:39 +0000 2019,346,221,0,0,imran khan:Imran_Khan:-0.9767803534439008;,1 -1,null;,null;,https://www.youtube.com/watch?v=LuYfs5uudT4&fe...
214,1179019429792899073,c22b6e89f89f712444db8e26680c5b6a,Tue Oct 01 13:05:11 +0000 2019,1694,103,1,1,ayushman bharat:Ayushman_Bharat_Yojana:-2.6523...,1 -1,narendramodi,null;,https://www.pscp.tv/w/cGM8YzMyMjExNTJ8MXJtR1BY...
215,1179020280498401281,827866e2bf2d7e01b3cdcd78f3a40ef4,Tue Oct 01 13:08:34 +0000 2019,142,211,0,0,null;,1 -1,uranusEli CartiSnippet,null;,null;
216,1179020886050893824,641a9eadf3b56e9957ffa925131683f8,Tue Oct 01 13:10:59 +0000 2019,188,139,25,12,to you all:To_You_All:-2.700490410686484;,2 -1,HardeepSPuri PMOIndia nsitharaman,AmrapaliFlatBuyers ReleaseStressFunds DreamValley,null;
217,1179021832365789184,f7c1302be7739e4ddc53241e5cf550e0,Tue Oct 01 13:14:44 +0000 2019,543,487,0,0,x360:Xbox_360:-1.0298500820034322;gamecube:Gam...,2 -1,null;,null;,null;
218,1179022430150500353,6601fdd4e62c73dbadee427045fc9ff4,Tue Oct 01 13:17:07 +0000 2019,2702,369,1,10,areola:Areola:-1.738429944867459;,2 -1,null;,null;,null;
219,1179022551520964608,f202a7ffab97d31e1b5b1df5612f15c4,Tue Oct 01 13:17:36 +0000 2019,1644,1384,65,76,china:China:-2.113921624336916;kidnapping:Kidn...,2 -1,TomCottonAR,HKPoliceGoneNuts HongKongProtester China70year...,null;

In [14]:
timecol = data['Timestamp']
timecol

0          Mon Sep 30 22:00:37 +0000 2019
1          Mon Sep 30 22:01:24 +0000 2019
2          Mon Sep 30 22:06:21 +0000 2019
3          Mon Sep 30 22:14:04 +0000 2019
4          Mon Sep 30 22:26:32 +0000 2019
                        ...
8077789    Thu Apr 30 21:49:23 +0000 2020
8077790    Thu Apr 30 21:51:39 +0000 2020
8077791    Thu Apr 30 21:51:49 +0000 2020
8077792    Thu Apr 30 21:56:06 +0000 2020
8077793    Thu Apr 30 21:57:51 +0000 2020
Name: Timestamp, Length: 8077794, dtype: object

In [9]:
'''
#Timestamp: Format ( "EEE MMM dd HH:mm:ss Z yyyy" ). ISOString => integer (e.g. 23517957).
import datetime
daykey = {"Sun":0,"Mon":1,"Tue":2,"Wed":3,"Thu":4,"Fri":5,"Sat":6}
#monthkey = {"Jan":1, "Feb":2,"Mar":3,"Apr":4,"May":5,"Jun":6,"Jul":7,"Aug":8,"Sep":9,"Oct":10,"Nov":11,"Dec":12}
day = []
#month = []
sec = [] #number of seconds from 1st Jan 2019
for i in timecol:
    t = i.split(" ")
    day.append(daykey[t[0]])
    #month.append(monthkey[t[1]])
    date = datetime.datetime.strptime(i, '%a %b %d %H:%M:%S +0000 %Y')
    sec.append(str((date - datetime.datetime(2019, 1, 1)).total_seconds())[:-2])

#test
print(day[:10])
#print(month[:10])
print(sec[:10])
'''

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
['23580037', '23580084', '23580381', '23580844', '23581592', '23582343', '23582583', '23582766', '23582827', '23582943']

In [16]:
def datetime_col(dataframe, col_name):
    ''' returns dataframe with added 2 columns - 1. day of week, 2.Int num of sec from 1/1/2019 '''
    daykey = {"Sun":0,"Mon":1,"Tue":2,"Wed":3,"Thu":4,"Fri":5,"Sat":6}
    day = []
    sec = []
    for i in dataframe[col_name]:
        t = i.split(" ")
        day.append(daykey[t[0]])
        date = datetime.datetime.strptime(i, '%a %b %d %H:%M:%S +0000 %Y')
        sec.append(str((date - datetime.datetime(2019, 1, 1)).total_seconds())[:-2])
    dataframe['Day of Week'] = pd.Series(day)
    dataframe['Time Int'] = pd.Series(sec)
    return dataframe

In [18]:
data = datetime_col(data, 'Timestamp')
data

,Tweet Id,Username,Timestamp,#Followers,#Friends,#Retweets,#Favorites,Entities,Sentiment,Mentions,Hashtags,URLs,Day of Week,Time Int
0,1178791787386814465,35234fe4a19cc1a3336095fb3780bcc1,Mon Sep 30 22:00:37 +0000 2019,619,770,0,0,null;,2 -1,null;,null;,null;,1,23580037
1,1178791985106153472,ea4592f39636d87af8fb4b17b7e2e4c0,Mon Sep 30 22:01:24 +0000 2019,36365,19344,13,17,nazi:Nazism:-2.742538749414189;blood money:Blo...,1 -4,null;,null;,https://twitter.com/himalayahawk/status/117766...,1,23580084
2,1178793230223183872,bf05d1888dd974fa4a8679c25e2ead03,Mon Sep 30 22:06:21 +0000 2019,5018,1933,0,0,vaccine:Vaccine:-2.6651530673745762;anti vaxxe...,2 -1,null;,null;,https://goo.gl/fb/uoeiPk:-:,1,23580381
3,1178795172206919680,eb8a99bca8945eab1d006750e9b75518,Mon Sep 30 22:14:04 +0000 2019,2219,971,0,0,muse:Muse_%28band%29:-2.1677823918620867;talki...,2 -1,null;,null;,null;,1,23580844
4,1178798309491822592,00695cf79d60e86a5d0f872f4358337a,Mon Sep 30 22:26:32 +0000 2019,9009,4943,26,89,people of northern ireland:People_of_Northern_...,2 -1,null;,VFS,null;,1,23581592
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8077789,1255977575806939136,d304c5f831a28e2a46ce1103cc8a40f2,Thu Apr 30 21:49:23 +0000 2020,45,236,0,0,bbc news:BBC_News:-0.4189977366734566;,1 -1,null;,null;,https://www.bbc.com/news/world-us-canada-52493...,4,41982563
8077790,1255978146228318208,ad97147abec2ec6fe2e575f36264a33e,Thu Apr 30 21:51:39 +0000 2020,5,74,0,0,null;,3 -1,null;,almost lockdown itvtonight,null;,4,41982699
8077791,1255978188267614208,c456c71a9e4d054714e2ca58c3d93fa2,Thu Apr 30 21:51:49 +0000 2020,46987,4953,38,125,free will:Free_will:-1.9738137854232647;there ...,2 -3,null;,null;,null;,4,41982709
8077792,1255979266115854336,bde2cd85338f0b68303e4702ff562557,Thu Apr 30 21:56:06 +0000 2020,21796,22109,0,0,social distancing:Social_distancing:-1.4103273...,1 -2,null;,null;,null;,4,41982966
8077793,1255979706513580036,a2a2726de83b4afaa8622efd50906e38,Thu Apr 30 21:57:51 +0000 2020,25,203,0,0,null;,2 -1,kylerobertsxx shanedawson,null;,null;,4,41983071

In [22]:
# Tokenizing SentiStrength Score
def sentiment_col(dataframe, col_name):
    dataframe["Positive"] = pd.Series([ int(x.split(' ')[0]) for x in data['Sentiment']])
    dataframe["Negative"] = pd.Series([ int(x.split(' ')[1]) for x in data['Sentiment']])
    dataframe["Sentiment Disparity"] = pd.Series([int(x.split(' ')[0])-int(x.split(' ')[1]) for x in data['Sentiment']])
    return dataframe

In [23]:
sentiment_col(data, 'Sentiment')

,Tweet Id,Username,Timestamp,#Followers,#Friends,#Retweets,#Favorites,Entities,Sentiment,Mentions,Hashtags,URLs,Day of Week,Time Int,Positive,Negative,Sentiment Disparity
0,1178791787386814465,35234fe4a19cc1a3336095fb3780bcc1,Mon Sep 30 22:00:37 +0000 2019,619,770,0,0,null;,2 -1,null;,null;,null;,1,23580037,2,-1,3
1,1178791985106153472,ea4592f39636d87af8fb4b17b7e2e4c0,Mon Sep 30 22:01:24 +0000 2019,36365,19344,13,17,nazi:Nazism:-2.742538749414189;blood money:Blo...,1 -4,null;,null;,https://twitter.com/himalayahawk/status/117766...,1,23580084,1,-4,5
2,1178793230223183872,bf05d1888dd974fa4a8679c25e2ead03,Mon Sep 30 22:06:21 +0000 2019,5018,1933,0,0,vaccine:Vaccine:-2.6651530673745762;anti vaxxe...,2 -1,null;,null;,https://goo.gl/fb/uoeiPk:-:,1,23580381,2,-1,3
3,1178795172206919680,eb8a99bca8945eab1d006750e9b75518,Mon Sep 30 22:14:04 +0000 2019,2219,971,0,0,muse:Muse_%28band%29:-2.1677823918620867;talki...,2 -1,null;,null;,null;,1,23580844,2,-1,3
4,1178798309491822592,00695cf79d60e86a5d0f872f4358337a,Mon Sep 30 22:26:32 +0000 2019,9009,4943,26,89,people of northern ireland:People_of_Northern_...,2 -1,null;,VFS,null;,1,23581592,2,-1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8077789,1255977575806939136,d304c5f831a28e2a46ce1103cc8a40f2,Thu Apr 30 21:49:23 +0000 2020,45,236,0,0,bbc news:BBC_News:-0.4189977366734566;,1 -1,null;,null;,https://www.bbc.com/news/world-us-canada-52493...,4,41982563,1,-1,2
8077790,1255978146228318208,ad97147abec2ec6fe2e575f36264a33e,Thu Apr 30 21:51:39 +0000 2020,5,74,0,0,null;,3 -1,null;,almost lockdown itvtonight,null;,4,41982699,3,-1,4
8077791,1255978188267614208,c456c71a9e4d054714e2ca58c3d93fa2,Thu Apr 30 21:51:49 +0000 2020,46987,4953,38,125,free will:Free_will:-1.9738137854232647;there ...,2 -3,null;,null;,null;,4,41982709,2,-3,5
8077792,1255979266115854336,bde2cd85338f0b68303e4702ff562557,Thu Apr 30 21:56:06 +0000 2020,21796,22109,0,0,social distancing:Social_distancing:-1.4103273...,1 -2,null;,null;,null;,4,41982966,1,-2,3
8077793,1255979706513580036,a2a2726de83b4afaa8622efd50906e38,Thu Apr 30 21:57:51 +0000 2020,25,203,0,0,null;,2 -1,kylerobertsxx shanedawson,null;,null;,4,41983071,2,-1,3

In [33]:
def scaledtransform(dataframe, cols):
    for col,m in cols:
        dataframe["scaled_" + col ] = dataframe[col].apply(lambda x: x/m)
        dataframe = dataframe.drop(col,1)
    return dataframe


def logtransform(dataframe,cols):
    for col in cols:
        dataframe["log_" + col ] = dataframe[col].apply(lambda x: np.log10(int(x)+1))
        dataframe = dataframe.drop(col,1)
    return dataframe

def ohetransform(dataframe, cols):
    for col in cols:
        one_hot = pd.get_dummies(dataframe[col])
        dataframe["ohe_" + col ] = one_hot.values.tolist()
        dataframe = dataframe.drop(col,1)
    return dataframe

def unpackcol(dataframe,cols):
    for col in cols:
        unpacked = pd.DataFrame(df[col].tolist(), columns=[f'{col}_{idx + 1}' for idx in range(len(df[col].values[0]))], index= dataframe.index)
        dataframe = dataframe.drop(col,axis=1)
        dataframe = pd.concat([dataframe, unpacked], axis=1, join='inner')
    return dataframe

In [34]:
'''
# Tokenizing SentiStrength Score
data["Positive"] = pd.Series([ int(x.split(' ')[0]) for x in data['Sentiment']])
data["Negative"] = pd.Series([ int(x.split(' ')[1]) for x in data['Sentiment']])
data["Sentiment Disparity"] = pd.Series([int(x.split(' ')[0])-int(x.split(' ')[1]) for x in data['Sentiment']])
data'''

'\n# Tokenizing SentiStrength Score\ndata["Positive"] = pd.Series([ int(x.split(\' \')[0]) for x in data[\'Sentiment\']])\ndata["Negative"] = pd.Series([ int(x.split(\' \')[1]) for x in data[\'Sentiment\']])\ndata["Sentiment Disparity"] = pd.Series([int(x.split(\' \')[0])-int(x.split(\' \')[1]) for x in data[\'Sentiment\']])\ndata'

In [35]:
'''
#Entities 
entities = data['Entities'].str.split(";")
entity_no = []
for ent in entities:
    ent.pop()
    if ent[0]=='null':
        entity_no.append(0)
    else:
        entity_no.append(len(ent))
data['No. of Entities'] = entity_no
data.head()'''

'\n#Entities \nentities = data[\'Entities\'].str.split(";")\nentity_no = []\nfor ent in entities:\n    ent.pop()\n    if ent[0]==\'null\':\n        entity_no.append(0)\n    else:\n        entity_no.append(len(ent))\ndata[\'No. of Entities\'] = entity_no\ndata.head()'

In [24]:
def entities_col(dataframe, col_name):
     #Entities 
    entities = dataframe[col_name].str.split(";")
    entity_no = []
    for ent in entities:
        ent.pop()
        if ent[0]=='null':
            entity_no.append(0)
        else:
            entity_no.append(len(ent))
    dataframe['No. of Entities'] = entity_no
    return dataframe

In [25]:
entities_col(data, 'Entities')

,Tweet Id,Username,Timestamp,#Followers,#Friends,#Retweets,#Favorites,Entities,Sentiment,Mentions,Hashtags,URLs,Day of Week,Time Int,Positive,Negative,Sentiment Disparity,No. of Entities
0,1178791787386814465,35234fe4a19cc1a3336095fb3780bcc1,Mon Sep 30 22:00:37 +0000 2019,619,770,0,0,null;,2 -1,null;,null;,null;,1,23580037,2,-1,3,0
1,1178791985106153472,ea4592f39636d87af8fb4b17b7e2e4c0,Mon Sep 30 22:01:24 +0000 2019,36365,19344,13,17,nazi:Nazism:-2.742538749414189;blood money:Blo...,1 -4,null;,null;,https://twitter.com/himalayahawk/status/117766...,1,23580084,1,-4,5,2
2,1178793230223183872,bf05d1888dd974fa4a8679c25e2ead03,Mon Sep 30 22:06:21 +0000 2019,5018,1933,0,0,vaccine:Vaccine:-2.6651530673745762;anti vaxxe...,2 -1,null;,null;,https://goo.gl/fb/uoeiPk:-:,1,23580381,2,-1,3,3
3,1178795172206919680,eb8a99bca8945eab1d006750e9b75518,Mon Sep 30 22:14:04 +0000 2019,2219,971,0,0,muse:Muse_%28band%29:-2.1677823918620867;talki...,2 -1,null;,null;,null;,1,23580844,2,-1,3,2
4,1178798309491822592,00695cf79d60e86a5d0f872f4358337a,Mon Sep 30 22:26:32 +0000 2019,9009,4943,26,89,people of northern ireland:People_of_Northern_...,2 -1,null;,VFS,null;,1,23581592,2,-1,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8077789,1255977575806939136,d304c5f831a28e2a46ce1103cc8a40f2,Thu Apr 30 21:49:23 +0000 2020,45,236,0,0,bbc news:BBC_News:-0.4189977366734566;,1 -1,null;,null;,https://www.bbc.com/news/world-us-canada-52493...,4,41982563,1,-1,2,1
8077790,1255978146228318208,ad97147abec2ec6fe2e575f36264a33e,Thu Apr 30 21:51:39 +0000 2020,5,74,0,0,null;,3 -1,null;,almost lockdown itvtonight,null;,4,41982699,3,-1,4,0
8077791,1255978188267614208,c456c71a9e4d054714e2ca58c3d93fa2,Thu Apr 30 21:51:49 +0000 2020,46987,4953,38,125,free will:Free_will:-1.9738137854232647;there ...,2 -3,null;,null;,null;,4,41982709,2,-3,5,2
8077792,1255979266115854336,bde2cd85338f0b68303e4702ff562557,Thu Apr 30 21:56:06 +0000 2020,21796,22109,0,0,social distancing:Social_distancing:-1.4103273...,1 -2,null;,null;,null;,4,41982966,1,-2,3,4
8077793,1255979706513580036,a2a2726de83b4afaa8622efd50906e38,Thu Apr 30 21:57:51 +0000 2020,25,203,0,0,null;,2 -1,kylerobertsxx shanedawson,null;,null;,4,41983071,2,-1,3,0

In [26]:
import logging
import numpy as np
import gensim.downloader

from gensim.models import Word2Vec
from gensim.test.utils import common_texts

logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

/Users/amarjyotkaur/opt/anaconda3/lib/python3.8/site-packages/gensim/similarities/__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)

In [51]:
#LOAD EMBEDDINGS
hashtag_embeddings = Word2Vec.load('/Users/amarjyotkaur/Downloads/hashtag_embeddings (1)')
mention_embeddings = Word2Vec.load('/Users/amarjyotkaur/Downloads/mention_embeddings')
hashtags = hashtag_embeddings.wv.index_to_key
mentions = mention_embeddings.wv.index_to_key

mentions

2021-08-02 12:51:07,129 : INFO : loading Word2Vec object from /Users/amarjyotkaur/Downloads/hashtag_embeddings (1)
2021-08-02 12:51:07,165 : INFO : loading wv recursively from /Users/amarjyotkaur/Downloads/hashtag_embeddings (1).wv.* with mmap=None
2021-08-02 12:51:07,166 : INFO : setting ignored attribute cum_table to None
2021-08-02 12:51:07,171 : INFO : Word2Vec lifecycle event {'fname': '/Users/amarjyotkaur/Downloads/hashtag_embeddings (1)', 'datetime': '2021-08-02T12:51:07.171772', 'gensim': '4.0.1', 'python': '3.8.8 (default, Apr 13 2021, 12:59:45) \n[Clang 10.0.0 ]', 'platform': 'macOS-10.16-x86_64-i386-64bit', 'event': 'loaded'}
2021-08-02 12:51:07,177 : INFO : loading Word2Vec object from /Users/amarjyotkaur/Downloads/mention_embeddings
2021-08-02 12:51:07,192 : INFO : loading wv recursively from /Users/amarjyotkaur/Downloads/mention_embeddings.wv.* with mmap=None
2021-08-02 12:51:07,194 : INFO : setting ignored attribute cum_table to None
2021-08-02 12:51:07,199 : INFO : Word2Vec lifecycle event {'fname': '/Users/amarjyotkaur/Downloads/mention_embeddings', 'datetime': '2021-08-02T12:51:07.199590', 'gensim': '4.0.1', 'python': '3.8.8 (default, Apr 13 2021, 12:59:45) \n[Clang 10.0.0 ]', 'platform': 'macOS-10.16-x86_64-i386-64bit', 'event': 'loaded'}

['realDonaldTrump',
 'PMOIndia',
 'narendramodi',
 'jaketapper',
 'YouTube',
 'BorisJohnson',
 'JoeBiden',
 'CNN',
 'POTUS',
 'WHO',
 'piersmorgan',
 'thomaskaine5',
 'NYGovCuomo',
 'Shop_Mask_USA',
 'gatewaypundit',
 'Gurmeetramrahim',
 'Frozan8',
 'NCDCgov',
 'WhiteHouse',
 'derasachasauda',
 'CDCgov',
 'MattHancock',
 'SpeakerPelosi',
 'BreitbartNews',
 'GOP',
 'Mask_Shop_USA',
 'PressSec',
 'nytimes',
 'BTS_twt',
 'Shop_Masks_USA',
 'IngrahamAngle',
 'thehill',
 'MoHFW_INDIA',
 'SkyNews',
 'RahulGandhi',
 'AmitShah',
 'BBCNews',
 'FoxNews',
 'DonaldJTrumpJr',
 'ChouhanShivraj',
 'ashokgehlot51',
 'GavinNewsom',
 'BarackObama',
 'washingtonpost',
 'MSNBC',
 'Medical_Masks_K',
 'elonmusk',
 'GenFlynn',
 'nsitharaman',
 'SecPompeo',
 'drharshvardhan',
 'kpophappenings_',
 'dbongino',
 'ArvindKejriwal',
 'ABC',
 'myogiadityanath',
 'Twitter',
 'VP',
 'UN',
 'HillaryClinton',
 'GovWhitmer',
 'CBSNews',
 'CMOMaharashtra',
 'MailOnline',
 'seanhannity',
 'ndtv',
 'NBCNews',
 'ImranKhanPTI',
 'NicolaSturgeon',
 'PIB_India',
 'SenSchumer',
 '10DowningStreet',
 'ygofficialblink',
 'aajtak',
 'brithume',
 'senatemajldr',
 'RealJamesWoods',
 'HardeepSPuri',
 'JustinTrudeau',
 'SaintRampalJiM',
 'Reuters',
 'JackPosobiec',
 'DrRPNishank',
 'HRDMinistry',
 'HMOIndia',
 'nypost',
 'INCIndia',
 'LindseyGrahamSC',
 'maddow',
 'Alyssa_Milano',
 'WSJ',
 'Keir_Starmer',
 'ANI',
 'BJP4India',
 'tarak9999',
 'sidharth_shukla',
 'GMB',
 'atrupar',
 'GovMurphy',
 'AUThackeray',
 'OfficeofUT',
 'BillGates',
 'DrTedros',
 'bbclaurak',
 'BBhuttoZardari',
 'OANN',
 'FinMinIndia',
 'jack',
 'fordnation',
 'funder',
 'NYCMayor',
 'RishiSunak',
 'kaitlancollins',
 'ProfKarolSikora',
 'BBCWorld',
 'GOPLeader',
 'MollyJongFast',
 'ArianaGrande',
 'politico',
 'COVIDNewsByMIB',
 'Breaking911',
 'AP',
 'Inevitable_ET',
 'GovMikeDeWine',
 'RandPaul',
 'PawanKalyan',
 'PiyushGoyal',
 'guardian',
 'RealCandaceO',
 'ChrisCuomo',
 'charliekirk11',
 'ChuckCallesto',
 'MoCA_GoI',
 'ZeeNews',
 'RepAdamSchiff',
 'SB19Official',
 'GovRonDeSantis',
 'gtconway3d',
 'KIITUniversity',
 'Acosta',
 'TuckerCarlson',
 'weareoneEXO',
 'CMOfficeUP',
 'Fmohnigeria',
 'CyrilRamaphosa',
 'TheJusticeDept',
 'CMOGuj',
 'ScottMorrisonMP',
 'business',
 'TheRickWilson',
 'benshapiro',
 'tedcruz',
 'MamataOfficial',
 'BSYBJP',
 'EricTrump',
 'MBuhari',
 'ChinaDaily',
 'MEAIndia',
 'ABPNews',
 'mrjamesob',
 'morningmika',
 'sudhirchaudhary',
 'CMofKarnataka',
 'weijia',
 'MIB_India',
 'PersevereEver',
 'Yamiche',
 'SidneyPowell1',
 'TheDemocrats',
 'MaskedSingerFOX',
 'CNBC',
 'afneil',
 'AOC',
 'achyuta_samanta',
 'catturd2',
 'GovernorTomWolf',
 'DrSJaishankar',
 'TomFitton',
 'KTRTRS',
 'SenateGOP',
 'itsJeffTiedrich',
 'LBC',
 'AlexBerenson',
 'DeAnna4Congress',
 'cnnbrk',
 'brianstelter',
 'timesofindia',
 'TakeThatEpi',
 'Etsy',
 'FLOTUS',
 'RailMinIndia',
 'JoeNBC',
 'BernieSanders',
 'DailyCaller',
 'IvankaTrump',
 'TXT_members',
 'SaeedGhani1',
 'CNNPolitics',
 'vijayrupanibjp',
 'jsolomonReports',
 'KTHopkins',
 'RichardGrenell',
 'MumbaiPolice',
 'SachinPilot',
 'republic',
 'PoliticsPot',
 'RajCMO',
 'justinbieber',
 'DominicRaab',
 'chancetherapper',
 'mygovindia',
 'airindiain',
 'latimes',
 'GOT7Official',
 'Swamy39',
 'RealMattCouch',
 'CovidIndiaSeva',
 'Cernovich',
 'MuradAliShahPPP',
 'XHNews',
 'HuXijin_GT',
 'BTS_SNIPPER',
 'abcnews',
 'ishehnaaz_gill',
 'DIPR_COVID19',
 'Nigel_Farage',
 'Peston',
 'kissfoundation',
 'GovTimWalz',
 'MOH_Kenya',
 'nbcnews',
 'kylegriffin1',
 'donnnie',
 'WHONigeria',
 'kenklippenstein',
 'TeamTrump',
 'News24',
 'joncoopertweets',
 'RaghusharmaINC',
 'Telegraph',
 'Mike_Pence',
 'FBI',
 'Conservatives',
 'marklevinshow',
 'GovPritzker',
 'DineshDSouza',
 'GOPChairwoman',
 'GoogleNews',
 'PDChina',
 'maggieNYT',
 'mitchellvii',
 'thedailybeast',
 'MaziNnamdiKanu',
 'foxandfriends',
 'Vickie627',
 'RBI',
 'JimRobe70184873',
 'Mongo3804',
 'SaraCarterDC',
 'jools6691',
 'jidesanwoolu',
 'mybmc',
 'mmpadellan',
 'TwitterSupport',
 'sambitswaraj',
 'TimesNow',
 'DigiVorr',
 'UNHumanRights',
 'rjmx',
 'hrw',
 'TomDoubting',
 'CMO_Odisha',
 'TertiusIII',
 'DrZweliMkhize',
 'ysjagan',
 'briantylercohen',
 'GodrejGroup',
 'SexCounseling',
 'NoScienceDenial',
 'malo_j',
 'GovInslee',
 'StateDept',
 'campbellclaret',
 'JoyAnnReid',
 'globaltimesnews',
 'DNC',
 'BethRigby',
 'ClarkeMicah',
 '60Minutes',
 'goldawardsTV',
 'TomiLahren',
 'KamalaHarris',
 'DDNewslive',
 'GregAbbott_TX',
 'chuckwoolery',
 'YahooNews',
 'NITIAayog',
 'andyguy',
 'JPNadda',
 'TheGod_Particle',
 'JuliaHB1',
 'Jones17Charlene',
 'realdonaldtrump',
 'cctip_io',
 'ChannelOTV',
 'Alexa17101614',
 'IndianExpress',
 'chrislhayes',
 'GlennB10809975',
 'RickySi16087724',
 'scotgov',
 'MikeAda69588676',
 'Acyn',
 'WmManry',
 'robtropper',
 'SlimJimJohn1',
 'network_gal',
 'FT',
 'the_resistor',
 'GovernorVA',
 'LadyVelvet_HFQ',
 'NPR',
 'BabeTruth2',
 'EU_Commission',
 'Jim_Jordan',
 'pledis_17',
 'Change',
 'MayorOfLA',
 'ewarren',
 'Sicut_Lupus',
 'UKChange',
 'Rev11_5',
 'ScottAdamsSays',
 'sardesairajdeep',
 'marcorubio',
 'CMOTamilNadu',
 'MysterySolvent',
 'dmgbnagar',
 'AfricaCDC',
 'badgervindaloo',
 'NitishKumar',
 'ScottGottliebMD',
 'dougstone2019',
 'TheRightMelissa',
 'RGanley',
 'odktiger',
 'adgpi',
 'doritmi',
 'rsprasad',
 'layzhang',
 'itvnews',
 'DHSCgovuk',
 'MiracleonIce21',
 'IndiaToday',
 'realDonaldTrump.',
 'JM_Scindia',
 'AndrewRChapman',
 'HuffPostPol',
 'AFP',
 'amazon',
 'Dev_Fadnavis',
 'laylow88861429',
 'BDUTT',
 'yashar',
 'LisaMei62',
 'CMMadhyaPradesh',
 'PandemicAction',
 'politicususa',
 'RyanAFournier',
 'IlhanMN',
 'perthppe',
 'NHSEngland',
 'americanism36',
 'Brian_Alford',
 'dcexaminer',
 'actorvijay',
 'Jay_see_see',
 'hotgirlspotted',
 'topleveltroll2',
 'Channel4News',
 'DrEOEhanire',
 'JoshuaPotash',
 'marinavibu609g',
 'PTI_News',
 'allisonpearson',
 'pritipatel',
 'cnni',
 'FMICNigeria',
 'lou_bruette',
 'LudMarx1',
 'eugenegu',
 'SolomonYue',
 'majorgauravarya',
 'himantabiswa',
 'KagutaMuseveni',
 'RudyGiuliani',
 'ICMRDELHI',
 'eBay',
 'mcfunny',
 'cmohry',
 'SatoshiFlipper',
 'ladygaga',
 'mlkhattar',
 'realDonaldTrump,',
 'priyankagandhi',
 'Eddy120876',
 'parscale',
 'htTweets',
 'SonuSood',
 'michaelgove',
 'ntrlbrnkllr66',
 'ianuragthakur',
 'johnrobertsFox',
 'ProjectLincoln',
 'PalmerReport',
 'DeraSachaSauda',
 'VikasKalantri',
 'kent_nye',
 'NASA',
 'nsouthern95',
 'PrisonPlanet',
 'zeerajasthan_',
 'SGRedCross',
 'CBCNews',
 'w_terrence',
 'davepperlmutter',
 'poshmarkapp',
 'ygtreasuremaker',
 'GovAbbott',
 'LeftyPuppetMan',
 'NextIDsg',
 'DelhiPolice',
 'MobilePunch',
 'Whiteleafent1',
 'imkimaaron',
 'UKLabour',
 'UNICEF',
 'MurderFancier',
 'SenTedCruz',
 'TheEconomist',
 'Angel1350852961',
 'Zilliqa',
 'Forbes',
 'nsitharamanoffc',
 'KISSFoundation',
 'scooterbraun',
 'cjtruth',
 'BurkesLawNYC',
 'gorillastyle',
 'DFS_India',
 'FoxBusiness',
 'UPGovt',
 'airnewsalerts',
 'PresidencyZA',
 'GayestSpiderMan',
 'CDCDirector',
 'RickAbt2',
 'Rose52413',
 'RockSergeant',
 'RPCovit',
 'bennyjohnson',
 'NateSilver538',
 'jkenney',
 'dvillella',
 'taylorswift13',
 'MariaBartiromo',
 'DanielAndrewsMP',
 'Team4Pakistan',
 'SecAzar',
 'BBCBreaking',
 'PIBHomeAffairs',
 'Amy_Siskind',
 'Stray_Kids',
 'dougducey',
 'TrumpSugar',
 'CBS',
 'Liberalist_Logi',
 'BeckyJohnson222',
 'x_nemesis1_x',
 'chicagosmayor',
 'globalnews',
 'antonioguterres',
 'smritiirani',
 'Comey',
 'NicolleDWallace',
 'real_defender',
 'maype7',
 'LionelMedia',
 'schooledump',
 'wef',
 'VincentCrypt46',
 'Monstercoyliar',
 'MinofHealthUG',
 'ASlavitt',
 'JansamparkMP',
 'maitlis',
 'RadioFreeTom',
 'agavecorn',
 'co_rapunzel4',
 'JaneEOpie',
 'NHSuk',
 'AAI_Official',
 'TajinderBagga',
 'globeandmail',
 'Suriya_offl',
 'ChrisJohnsonMD',
 'rashtrapatibhvn',
 'Rocket_1981',
 'RosaRubicon',
 '_mamadeb',
 'Melanie33720945',
 'carlsmythe',
 'acneonmyshirt',
 'FrankDElia7',
 'love_trump2020',
 'PPersnickety',
 'susannareid100',
 'Facebook',
 'HouseGOP',
 'JeffreeStar',
 'ClayTravis',
 'lewis_goodall',
 'GovSisolak',
 'DrJudyAMikovits',
 'PHE_uk',
 'SenatorDurbin',
 'netflix',
 'JudicialWatch',
 'jkellyca',
 'BillKristol',
 'NC_Governor',
 'johncardillo',
 'Grandma_Boom',
 'JustSayingWhat1',
 'PrakashJavdekar',
 'BlueAngels',
 'rohitksingh',
 'TimRunsHisMouth',
 'asadowaisi',
 'ColinCDawson',
 'SariellaHerself',
 'businessinsider',
 'drdineshbjp',
 'capt_amarinder',
 'GurmeetRamRahim',
 'orna_verum',
 'stoolpresidente',
 'ddale8',
 'NewIndianXpress',
 'SlsStudios',
 'MassGovernor',
 'HouseDemocrats',
 'M0sstr00per',
 'Nic6454',
 'Independent',
 'TheOldOlaf',
 'SB_Projects',
 'patkiddlehopper',
 'USATODAY',
 'KayBurley',
 'rulesviolation',
 'SaharaReporters',
 'US_FDA',
 'janforney1',
 'rl_montana',
 'HazyPeter',
 'DavidSkelton909',
 'RobertMcCowan1',
 'EvaNestrick',
 'mePaulaThompson',
 'ianfmusgrave',
 'Janwithay',
 'forbes',
 'Mental_Universe',
 'dallasrbaird',
 'GualcoJodie',
 'TIME',
 'Jeeneree',
 'THEMAMAELEPHANT',
 'A_Draeros',
 'doris03763159',
 'SarahGould_SA',
 'Cherfan4ever1',
 'wildwillow65',
 'TelanganaCMO',
 'CBS_Herridge',
 'markie_kmarky8',
 'DudekLinda',
 'SpokespersonCHN',
 'Tsunami_64',
 'vonderleyen',
 'SenTomCotton',
 'Itridpm',
 'KamVTV',
 'Plasticdoe',
 'LeoVaradkar',
 'JeffreyGuterman',
 'waltshaub',
 'akvawe66',
 'SpaceForceBravo',
 'Jamie_Foxworthy',
 'adamboultonSKY',
 '1_2_F_U',
 'impeachqueen',
 'Jaxhomegirl',
 'carolecadwalla',
 'Catheri77148739',
 'KevinVesey',
 'financialtimes',
 'mkraju',
 'MZHemingway',
 'suspersists',
 'Swags_D17',
 'HHSGov',
 'the_hindu',
 'PJMoore1958',
 'donlemon',
 'denyessence',
 'MovingEternity',
 'SpaceX',
 'Freewillburnya',
 'MarshaBlackburn',
 'tedlieu',
 'IAF_MCC',
 'PippaCrerar',
 'RestlessNews',
 'KellyannePolls',
 'DriftlessProf',
 'GodIfound',
 'ShercoSherrill',
 'TeaPainUSA',
 "realDonaldTrump's",
 'SteveSchmidtSES',
 'msisodia',
 'AdamParkhomenko',
 'zazzle',
 'SenSanders',
 'dananessel',
 'MacBaird13',
 'rajnathsingh',
 'AndrewYang',
 'LudmilaKliegl',
 'NICKIMINAJ',
 'B52Malmet',
 'Robyn_CherCrew',
 'blondjewels',
 'GovMLG',
 'Mooncatadams',
 'DPJHodges',
 '_ReaalAmerican_',
 'misshellca',
 'AJEnglish',
 'Naveen_Odisha',
 'krebiozen',
 'metpoliceuk',
 'OfficialMonstaX',
 'KEEMSTAR',
 'DrEricDing',
 'PPercussionist',
 'greggutfeld',
 'DGCAIndia',
 'CTVNews',
 'HobbyConnector',
 'azrielshields',
 'thedemorats',
 'realDonaldTrump’s',
 'MrAndyNgo',
 'PattiKimble',
 'TheTeamPatriot',
 'WarRoomPandemic',
 'Lawrence',
 'nbstv',
 'zlj517',
 'HenryWhitman7',
 'KarmaLovesTrump',
 'TrishBeMe',
 'hunterscider',
 'iamsrk',
 'gurleysgrl',
 'OregonGovBrown',
 'AngrierWHStaff',
 'Rodeson42',
 'JoeySalads',
 'JohnCornyn',
 'medwoman1',
 'pepper_gone_',
 'thewire_in',
 'cspanwj']

In [52]:
mention_embeddings.wv['realDonaldTrump']

array([ 0.5991303 , -0.10410535,  0.23690729, -0.23115875, -0.961905  ,
       -0.11418784,  0.12405131,  0.4196795 , -1.493182  , -0.20270342,
        1.2276924 , -1.3593616 , -0.19556278,  0.27365074,  0.32451993,
        1.9415929 , -0.20647514, -0.17526582, -0.69910485, -1.6436449 ,
        1.3161302 , -0.17269903, -0.5424232 ,  1.0386076 ,  1.062889  ],
      dtype=float32)

In [53]:
len(mention_embeddings.wv['realDonaldTrump'])

25

In [35]:
'''
ls = []
for i in data['Mentions']:
    if i in mentions and i!="null;":
        ls.append(mention_embeddings.wv[i])
    else:
        ls.append(np.zeros((25,), dtype=int))
data['Mention Embedding'] = pd.Series(ls)
'''

In [43]:
'''
ls = []
for i in data['Hashtags']:
    if i in hashtags and i!="null;":
        ls.append(hashtag_embeddings.wv[i])
    else:
        ls.append(np.zeros((25,), dtype=int))
data['Hashtag Embedding'] = pd.Series(ls)
'''

In [27]:
def hashtag_col(dataframe, col_name):
    #LOAD EMBEDDINGS
    hashtag_embeddings = Word2Vec.load('/Users/amarjyotkaur/Downloads/hashtag_embeddings (1)')
    hashtags = hashtag_embeddings.wv.index_to_key
    ls = []
    for i in dataframe['Hashtags']:
        if i in hashtags and i!="null;":
            ls.append(hashtag_embeddings.wv[i])
            length = len(hashtag_embeddings.wv[i])
        else:
             ls.append(np.zeros((25,), dtype=int))
    for i in range(length):
        dataframe['Hashtag Emb'+str(i)] = pd.Series([x[i] for x in ls])
    return dataframe

def mention_col(dataframe, col_name):
    #LOAD EMBEDDINGS
    mention_embeddings = Word2Vec.load('/Users/amarjyotkaur/Downloads/mention_embeddings')
    mentions = mention_embeddings.wv.index_to_key
    ls = []
    for i in dataframe['Mentions']:
        if i in mentions and i!="null;":
            ls.append(mention_embeddings.wv[i])
            length = len(mention_embeddings.wv[i])
        else:
             ls.append(np.zeros((25,), dtype=int))
    for i in range(length):
        dataframe['Mention Emb'+str(i)] = pd.Series([x[i] for x in ls])
    return dataframe

In [28]:
hashtag_col(data, 'Hashtags')
mention_col(data, "Mentions")

2021-08-02 22:52:09,803 : INFO : loading Word2Vec object from /Users/amarjyotkaur/Downloads/hashtag_embeddings (1)
2021-08-02 22:52:09,813 : INFO : loading wv recursively from /Users/amarjyotkaur/Downloads/hashtag_embeddings (1).wv.* with mmap=None
2021-08-02 22:52:09,814 : INFO : setting ignored attribute cum_table to None
2021-08-02 22:52:09,828 : INFO : Word2Vec lifecycle event {'fname': '/Users/amarjyotkaur/Downloads/hashtag_embeddings (1)', 'datetime': '2021-08-02T22:52:09.828658', 'gensim': '4.0.1', 'python': '3.8.8 (default, Apr 13 2021, 12:59:45) \n[Clang 10.0.0 ]', 'platform': 'macOS-10.16-x86_64-i386-64bit', 'event': 'loaded'}
2021-08-02 22:54:00,984 : INFO : loading Word2Vec object from /Users/amarjyotkaur/Downloads/mention_embeddings
2021-08-02 22:54:00,989 : INFO : loading wv recursively from /Users/amarjyotkaur/Downloads/mention_embeddings.wv.* with mmap=None
2021-08-02 22:54:00,989 : INFO : setting ignored attribute cum_table to None
2021-08-02 22:54:00,994 : INFO : Word2Vec lifecycle event {'fname': '/Users/amarjyotkaur/Downloads/mention_embeddings', 'datetime': '2021-08-02T22:54:00.994208', 'gensim': '4.0.1', 'python': '3.8.8 (default, Apr 13 2021, 12:59:45) \n[Clang 10.0.0 ]', 'platform': 'macOS-10.16-x86_64-i386-64bit', 'event': 'loaded'}

,Tweet Id,Username,Timestamp,#Followers,#Friends,#Retweets,#Favorites,Entities,Sentiment,Mentions,...,Mention Emb15,Mention Emb16,Mention Emb17,Mention Emb18,Mention Emb19,Mention Emb20,Mention Emb21,Mention Emb22,Mention Emb23,Mention Emb24
0,1178791787386814465,35234fe4a19cc1a3336095fb3780bcc1,Mon Sep 30 22:00:37 +0000 2019,619,770,0,0,null;,2 -1,null;,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1178791985106153472,ea4592f39636d87af8fb4b17b7e2e4c0,Mon Sep 30 22:01:24 +0000 2019,36365,19344,13,17,nazi:Nazism:-2.742538749414189;blood money:Blo...,1 -4,null;,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1178793230223183872,bf05d1888dd974fa4a8679c25e2ead03,Mon Sep 30 22:06:21 +0000 2019,5018,1933,0,0,vaccine:Vaccine:-2.6651530673745762;anti vaxxe...,2 -1,null;,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1178795172206919680,eb8a99bca8945eab1d006750e9b75518,Mon Sep 30 22:14:04 +0000 2019,2219,971,0,0,muse:Muse_%28band%29:-2.1677823918620867;talki...,2 -1,null;,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1178798309491822592,00695cf79d60e86a5d0f872f4358337a,Mon Sep 30 22:26:32 +0000 2019,9009,4943,26,89,people of northern ireland:People_of_Northern_...,2 -1,null;,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8077789,1255977575806939136,d304c5f831a28e2a46ce1103cc8a40f2,Thu Apr 30 21:49:23 +0000 2020,45,236,0,0,bbc news:BBC_News:-0.4189977366734566;,1 -1,null;,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8077790,1255978146228318208,ad97147abec2ec6fe2e575f36264a33e,Thu Apr 30 21:51:39 +0000 2020,5,74,0,0,null;,3 -1,null;,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8077791,1255978188267614208,c456c71a9e4d054714e2ca58c3d93fa2,Thu Apr 30 21:51:49 +0000 2020,46987,4953,38,125,free will:Free_will:-1.9738137854232647;there ...,2 -3,null;,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8077792,1255979266115854336,bde2cd85338f0b68303e4702ff562557,Thu Apr 30 21:56:06 +0000 2020,21796,22109,0,0,social distancing:Social_distancing:-1.4103273...,1 -2,null;,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8077793,1255979706513580036,a2a2726de83b4afaa8622efd50906e38,Thu Apr 30 21:57:51 +0000 2020,25,203,0,0,null;,2 -1,kylerobertsxx shanedawson,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
'''
ls = []
for i in data['Hashtags']:
    if i in hashtags and i!="null;":
        ls.append(hashtag_embeddings.wv[i])
        length = len(hashtag_embeddings.wv[i])
    else:
         ls.append(np.zeros((25,), dtype=int))
for i in range(length):
    data['Hashtag Emb'+str(i)] = pd.Series([x[i] for x in ls])
data'''

'\nls = []\nfor i in data[\'Hashtags\']:\n    if i in hashtags and i!="null;":\n        ls.append(hashtag_embeddings.wv[i])\n        length = len(hashtag_embeddings.wv[i])\n    else:\n         ls.append(np.zeros((25,), dtype=int))\nfor i in range(length):\n    data[\'Hashtag Emb\'+str(i)] = pd.Series([x[i] for x in ls])\ndata'

In [30]:
'''
ls = []
for i in data['Mentions']:
    if i in mentions and i!="null;":
        ls.append(mention_embeddings.wv[i])
       
    else:
         ls.append(np.zeros((25,), dtype=int))
for i in range(25):
    data['Mention Emb'+str(i)] = pd.Series([x[i] for x in ls])
data
'''

'\nls = []\nfor i in data[\'Mentions\']:\n    if i in mentions and i!="null;":\n        ls.append(mention_embeddings.wv[i])\n       \n    else:\n         ls.append(np.zeros((25,), dtype=int))\nfor i in range(25):\n    data[\'Mention Emb\'+str(i)] = pd.Series([x[i] for x in ls])\ndata\n'

In [31]:
data_new = data.copy(deep=True)

for x in ['Tweet Id', 'Timestamp','Entities','Sentiment', 'Mentions', 'Hashtags', 'URLs']:
    del data_new[x]
data_new

,Username,#Followers,#Friends,#Retweets,#Favorites,Day of Week,Time Int,Positive,Negative,Sentiment Disparity,...,Mention Emb15,Mention Emb16,Mention Emb17,Mention Emb18,Mention Emb19,Mention Emb20,Mention Emb21,Mention Emb22,Mention Emb23,Mention Emb24
0,35234fe4a19cc1a3336095fb3780bcc1,619,770,0,0,1,23580037,2,-1,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ea4592f39636d87af8fb4b17b7e2e4c0,36365,19344,13,17,1,23580084,1,-4,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,bf05d1888dd974fa4a8679c25e2ead03,5018,1933,0,0,1,23580381,2,-1,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,eb8a99bca8945eab1d006750e9b75518,2219,971,0,0,1,23580844,2,-1,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,00695cf79d60e86a5d0f872f4358337a,9009,4943,26,89,1,23581592,2,-1,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8077789,d304c5f831a28e2a46ce1103cc8a40f2,45,236,0,0,4,41982563,1,-1,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8077790,ad97147abec2ec6fe2e575f36264a33e,5,74,0,0,4,41982699,3,-1,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8077791,c456c71a9e4d054714e2ca58c3d93fa2,46987,4953,38,125,4,41982709,2,-3,5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8077792,bde2cd85338f0b68303e4702ff562557,21796,22109,0,0,4,41982966,1,-2,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8077793,a2a2726de83b4afaa8622efd50906e38,25,203,0,0,4,41983071,2,-1,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [36]:
df=scaledtransform(data_new,[("Positive",5),("Negative",-5), ("Sentiment Disparity",10)])
df

,Username,#Followers,#Friends,#Retweets,#Favorites,Day of Week,Time Int,No. of Entities,Hashtag Emb0,Hashtag Emb1,...,Mention Emb18,Mention Emb19,Mention Emb20,Mention Emb21,Mention Emb22,Mention Emb23,Mention Emb24,scaled_Positive,scaled_Negative,scaled_Sentiment Disparity
0,35234fe4a19cc1a3336095fb3780bcc1,619,770,0,0,1,23580037,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4,0.2,0.3
1,ea4592f39636d87af8fb4b17b7e2e4c0,36365,19344,13,17,1,23580084,2,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.8,0.5
2,bf05d1888dd974fa4a8679c25e2ead03,5018,1933,0,0,1,23580381,3,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4,0.2,0.3
3,eb8a99bca8945eab1d006750e9b75518,2219,971,0,0,1,23580844,2,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4,0.2,0.3
4,00695cf79d60e86a5d0f872f4358337a,9009,4943,26,89,1,23581592,2,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4,0.2,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8077789,d304c5f831a28e2a46ce1103cc8a40f2,45,236,0,0,4,41982563,1,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.2,0.2
8077790,ad97147abec2ec6fe2e575f36264a33e,5,74,0,0,4,41982699,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6,0.2,0.4
8077791,c456c71a9e4d054714e2ca58c3d93fa2,46987,4953,38,125,4,41982709,2,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4,0.6,0.5
8077792,bde2cd85338f0b68303e4702ff562557,21796,22109,0,0,4,41982966,4,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.4,0.3
8077793,a2a2726de83b4afaa8622efd50906e38,25,203,0,0,4,41983071,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4,0.2,0.3

In [37]:
df=logtransform(df,["#Retweets","#Followers", "#Friends", "No. of Entities","#Favorites", "Time Int"])
df

,Username,Day of Week,Hashtag Emb0,Hashtag Emb1,Hashtag Emb2,Hashtag Emb3,Hashtag Emb4,Hashtag Emb5,Hashtag Emb6,Hashtag Emb7,...,Mention Emb24,scaled_Positive,scaled_Negative,scaled_Sentiment Disparity,log_#Retweets,log_#Followers,log_#Friends,log_No. of Entities,log_#Favorites,log_Time Int
0,35234fe4a19cc1a3336095fb3780bcc1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.4,0.2,0.3,0.000000,2.792392,2.887054,0.000000,0.000000,7.372545
1,ea4592f39636d87af8fb4b17b7e2e4c0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.2,0.8,0.5,1.146128,4.560696,4.286569,0.477121,1.255273,7.372545
2,bf05d1888dd974fa4a8679c25e2ead03,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.4,0.2,0.3,0.000000,3.700617,3.286456,0.602060,0.000000,7.372551
3,eb8a99bca8945eab1d006750e9b75518,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.4,0.2,0.3,0.000000,3.346353,2.987666,0.477121,0.000000,7.372559
4,00695cf79d60e86a5d0f872f4358337a,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.4,0.2,0.3,1.431364,3.954725,3.694078,0.477121,1.954243,7.372573
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8077789,d304c5f831a28e2a46ce1103cc8a40f2,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.2,0.2,0.2,0.000000,1.662758,2.374748,0.301030,0.000000,7.623069
8077790,ad97147abec2ec6fe2e575f36264a33e,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.6,0.2,0.4,0.000000,0.778151,1.875061,0.000000,0.000000,7.623070
8077791,c456c71a9e4d054714e2ca58c3d93fa2,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.4,0.6,0.5,1.591065,4.671987,3.694956,0.477121,2.100371,7.623070
8077792,bde2cd85338f0b68303e4702ff562557,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.2,0.4,0.3,0.000000,4.338397,4.344589,0.698970,0.000000,7.623073
8077793,a2a2726de83b4afaa8622efd50906e38,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.4,0.2,0.3,0.000000,1.414973,2.309630,0.000000,0.000000,7.623074

In [38]:
df = ohetransform(df, ["Day of Week"])
df

,Username,Hashtag Emb0,Hashtag Emb1,Hashtag Emb2,Hashtag Emb3,Hashtag Emb4,Hashtag Emb5,Hashtag Emb6,Hashtag Emb7,Hashtag Emb8,...,scaled_Positive,scaled_Negative,scaled_Sentiment Disparity,log_#Retweets,log_#Followers,log_#Friends,log_No. of Entities,log_#Favorites,log_Time Int,ohe_Day of Week
0,35234fe4a19cc1a3336095fb3780bcc1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.4,0.2,0.3,0.000000,2.792392,2.887054,0.000000,0.000000,7.372545,"[0, 1, 0, 0, 0, 0, 0]"
1,ea4592f39636d87af8fb4b17b7e2e4c0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.2,0.8,0.5,1.146128,4.560696,4.286569,0.477121,1.255273,7.372545,"[0, 1, 0, 0, 0, 0, 0]"
2,bf05d1888dd974fa4a8679c25e2ead03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.4,0.2,0.3,0.000000,3.700617,3.286456,0.602060,0.000000,7.372551,"[0, 1, 0, 0, 0, 0, 0]"
3,eb8a99bca8945eab1d006750e9b75518,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.4,0.2,0.3,0.000000,3.346353,2.987666,0.477121,0.000000,7.372559,"[0, 1, 0, 0, 0, 0, 0]"
4,00695cf79d60e86a5d0f872f4358337a,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.4,0.2,0.3,1.431364,3.954725,3.694078,0.477121,1.954243,7.372573,"[0, 1, 0, 0, 0, 0, 0]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8077789,d304c5f831a28e2a46ce1103cc8a40f2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.2,0.2,0.2,0.000000,1.662758,2.374748,0.301030,0.000000,7.623069,"[0, 0, 0, 0, 1, 0, 0]"
8077790,ad97147abec2ec6fe2e575f36264a33e,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.6,0.2,0.4,0.000000,0.778151,1.875061,0.000000,0.000000,7.623070,"[0, 0, 0, 0, 1, 0, 0]"
8077791,c456c71a9e4d054714e2ca58c3d93fa2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.4,0.6,0.5,1.591065,4.671987,3.694956,0.477121,2.100371,7.623070,"[0, 0, 0, 0, 1, 0, 0]"
8077792,bde2cd85338f0b68303e4702ff562557,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.2,0.4,0.3,0.000000,4.338397,4.344589,0.698970,0.000000,7.623073,"[0, 0, 0, 0, 1, 0, 0]"
8077793,a2a2726de83b4afaa8622efd50906e38,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.4,0.2,0.3,0.000000,1.414973,2.309630,0.000000,0.000000,7.623074,"[0, 0, 0, 0, 1, 0, 0]"

In [39]:
#df = unpackcol(df,["Mention Embedding", "Hashtag Embedding", "ohe_Day of Week"])
df = unpackcol(df, ["ohe_Day of Week"])
df

,Username,Hashtag Emb0,Hashtag Emb1,Hashtag Emb2,Hashtag Emb3,Hashtag Emb4,Hashtag Emb5,Hashtag Emb6,Hashtag Emb7,Hashtag Emb8,...,log_No. of Entities,log_#Favorites,log_Time Int,ohe_Day of Week_1,ohe_Day of Week_2,ohe_Day of Week_3,ohe_Day of Week_4,ohe_Day of Week_5,ohe_Day of Week_6,ohe_Day of Week_7
0,35234fe4a19cc1a3336095fb3780bcc1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,7.372545,0,1,0,0,0,0,0
1,ea4592f39636d87af8fb4b17b7e2e4c0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.477121,1.255273,7.372545,0,1,0,0,0,0,0
2,bf05d1888dd974fa4a8679c25e2ead03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.602060,0.000000,7.372551,0,1,0,0,0,0,0
3,eb8a99bca8945eab1d006750e9b75518,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.477121,0.000000,7.372559,0,1,0,0,0,0,0
4,00695cf79d60e86a5d0f872f4358337a,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.477121,1.954243,7.372573,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8077789,d304c5f831a28e2a46ce1103cc8a40f2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.301030,0.000000,7.623069,0,0,0,0,1,0,0
8077790,ad97147abec2ec6fe2e575f36264a33e,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,7.623070,0,0,0,0,1,0,0
8077791,c456c71a9e4d054714e2ca58c3d93fa2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.477121,2.100371,7.623070,0,0,0,0,1,0,0
8077792,bde2cd85338f0b68303e4702ff562557,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.698970,0.000000,7.623073,0,0,0,0,1,0,0
8077793,a2a2726de83b4afaa8622efd50906e38,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,7.623074,0,0,0,0,1,0,0

In [40]:
#df = df.drop(["Month","Username"],1)
df = df.drop(["Username"],1)
df

,Hashtag Emb0,Hashtag Emb1,Hashtag Emb2,Hashtag Emb3,Hashtag Emb4,Hashtag Emb5,Hashtag Emb6,Hashtag Emb7,Hashtag Emb8,Hashtag Emb9,...,log_No. of Entities,log_#Favorites,log_Time Int,ohe_Day of Week_1,ohe_Day of Week_2,ohe_Day of Week_3,ohe_Day of Week_4,ohe_Day of Week_5,ohe_Day of Week_6,ohe_Day of Week_7
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,7.372545,0,1,0,0,0,0,0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.477121,1.255273,7.372545,0,1,0,0,0,0,0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.602060,0.000000,7.372551,0,1,0,0,0,0,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.477121,0.000000,7.372559,0,1,0,0,0,0,0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.477121,1.954243,7.372573,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8077789,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.301030,0.000000,7.623069,0,0,0,0,1,0,0
8077790,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,7.623070,0,0,0,0,1,0,0
8077791,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.477121,2.100371,7.623070,0,0,0,0,1,0,0
8077792,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.698970,0.000000,7.623073,0,0,0,0,1,0,0
8077793,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,7.623074,0,0,0,0,1,0,0

In [41]:
df.to_pickle("data_processed.pkl")

In [42]:
sampledf = df.sample(n=100000) #1mil
sampledf

,Hashtag Emb0,Hashtag Emb1,Hashtag Emb2,Hashtag Emb3,Hashtag Emb4,Hashtag Emb5,Hashtag Emb6,Hashtag Emb7,Hashtag Emb8,Hashtag Emb9,...,log_No. of Entities,log_#Favorites,log_Time Int,ohe_Day of Week_1,ohe_Day of Week_2,ohe_Day of Week_3,ohe_Day of Week_4,ohe_Day of Week_5,ohe_Day of Week_6,ohe_Day of Week_7
2184594,0.831879,-0.226250,0.756643,0.184878,0.487396,-0.915382,0.175066,1.204610,0.368475,-0.723571,...,0.477121,0.477121,7.503540,0,0,0,0,0,0,1
2617969,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.602060,2.942504,7.537087,0,1,0,0,0,0,0
4510975,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,7.588201,0,0,1,0,0,0,0
5622386,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.477121,0.698970,7.601872,0,0,1,0,0,0,0
61138,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,7.416783,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6822516,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.698970,0.778151,7.608417,0,0,1,0,0,0,0
480958,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,7.416198,0,0,1,0,0,0,0
3207562,0.798245,0.040597,0.250579,-0.264156,0.237985,0.186510,-0.222812,0.997549,-0.593419,-0.681417,...,0.301030,0.000000,7.577682,0,0,0,0,0,1,0
7026027,0.231246,-0.265176,-0.012497,0.110691,-0.113339,0.066234,-0.013896,0.488121,0.240162,-0.510032,...,0.301030,0.845098,7.610449,0,0,0,0,1,0,0
2673779,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.301030,0.000000,7.558704,1,0,0,0,0,0,0

In [43]:
sampledf.to_pickle("sample_data_processed.pkl")